name: Deploy release artifact

on:
  release:
    types: [published]

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64
      - name: Set tag name in env
        run: echo "GITHUB_TAG=$(echo "${GITHUB_REF##*/}")" >> $GITHUB_ENV
      - name: Set version number
        run: mvn --batch-mode versions:set -DnewVersion=${GITHUB_TAG} versions:commit
      - name: Run tests
        run: mvn install test --batch-mode --no-transfer-progress
      - name: Build for docker
        run: mvn clean install -DskipTests=true -Pdocker --batch-mode
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Docker ready deployment package
          path: ComponentRegistry/target/component-registry-rest-*-docker.tar.gz
          compression-level: 1
          if-no-files-found: error

### TRAVIS
# before_deploy:
#   - yes | gem update --system --force
#   - gem install bundler
#   - gem install faraday-net_http -v '3.3.0' # Fix faraday version
#   - gem install uri
#   - gem install logger
# deploy:
#   provider: releases
#   prerelease: true
#   token: "${GITHUB_DEPLOY_TOKEN}"
#   file: "ComponentRegistry/target/component-registry-rest-${TRAVIS_TAG}-docker.tar.gz"
#   skip_cleanup: true
#   on:
#     tags: true